# Generated by Django 3.1.7 on 2021-04-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
    ]
